--CREATE TABLE person(
--    id UUID NOT NULL PRIMARY KEY,
--    name VARCHAR(100) NOT NULL
--)

--CREATE TABLE TestTable(
--    userID    int ,
--    LastName  VARCHAR(100) ,
--    FirstName VARCHAR(100) ,
--    Address VARCHAR(100) ,
--    City VARCHAR(100)
--
--)
